
eureka:
  instance:
    instance-id:  ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/

server:
  port: 8876
spring:
  application:
    name: hystrix-client
logging:
  level:
     org.springframework: debug
#OpenFeign是自带Hystrix,但是默认没有打开
feign:
  hystrix:
    enabled: true
ribbon:
  eureka:
    enabled: true


