sms:
  retry-limitation-minutes: 1
  vaildity-minute: 3
  types:
    - register
    - login
management:
  endpoints:
     web:
        exposure:
          exclude:
          include: info,health,beans,loggers